### ISSUE TITLE
generate_container_user permissions error

### ISSUE THREAD

**Issue by ryanj** [openshift/s2i-nodejs#101]
I'm getting a "Crash loop back off" when deploying images built on top of the RHEL nodejs-0.10 image with OSE v3.2.0.20

This is what shows up in the log:
`/opt/app-root/etc/generate_container_user: line 10: /opt/app-root/etc/passwd: Permission denied`

**Comment by bparees** [comment]
this has been fixed, image just hasn't been published yet:
https://github.com/openshift/s2i-nodejs/pull/100
https://bugzilla.redhat.com/show_bug.cgi?id=1336263

**Comment by bretm** [comment]
This is hitting me on the OpenShift Online (Next-gen) preview, not sure of the right escalation path there :/

**Comment by bparees** [comment]
@smarterclayton did you talk to ops about updating the nodejs image on online?

**Comment by smarterclayton** [comment]
No

**Comment by bparees** [comment]
@bretm's problem was resolved after some irc discussion, online preview has some configuration to be done, but the latest nodejs image should now be used on all nodes.
