### ISSUE TITLE
Update Nodejs version

### ISSUE THREAD

**Issue by nudoru** [openshift/s2i-nodejs#91]
I encountered issues NPM installing my app in the container Node.js 0.10 container

remote: npm ERR! EEXIST, open '/var/lib/openshift/570405602d52715852000146/.npm/9edcc8i s61-0146-npm-json5-0-4-0-package-tgz.lock'
remote: File exists: /var/lib/openshift/570405602d52715852000146/.npm/9edcc861-0146-npm-json5-0-4-0-package-tgz.lock
remote: Move it away, and try again.

The error seem similar to this one: https://github.com/fbrctr/fabricator/issues/77

I create a new app with the Node.js (latest) container and it worked just fine.

Suggest updating the version of Node.js in this container so that NPM installs work successfully.

**Comment by bparees** [comment]
@mfojtik @hhorak I thought we got an updated version of npm that fixed some lock issues?

@nudoru which image are you using?  centos or rhel?  and how are you using it?  (s2i? openshift?)  Can you confirm you're using the latest image?

**Comment by nudoru** [comment]
@bparees I created a new app from the Openshift web console on the Node.js 0.10 cartridge. When submitting changes w/ Git, it would bonk and error out every time when it tried to build.

**Comment by bparees** [comment]
@nudoru can you point us to the git repo you're building so we can do a recreate?

**Comment by nudoru** [comment]
I was building this https://github.com/nudoru/React-Starter

**Comment by eliskasl** [comment]
@bparees, apparently, the CentOS nodejs010 collection was never updated. @humaton, @kasicka, please make sure to get the latest changes in as soon as possible.

**Comment by bparees** [comment]
@eliskasl thanks.. @humaton @kasicka can you update this PR once the new collection is available so i can rebulid the nodejs centos image?

**Comment by kasicka** [comment]
Nodejs 0.10 collection is finally updated.

**Comment by bparees** [comment]
has been rebuilt and pushed.
